# Generated by Django 3.2.7 on 2021-09-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=50, unique=True, verbose_name='Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.profile', verbose_name='Profile')),
            ],
        ),
    ]
