# Generated by Django 3.2.7 on 2021-09-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group'},
        ),
    ]
