# Generated by Django 3.2.7 on 2021-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='default_group', max_length=50, verbose_name='Group'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('profile', 'group_name')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='unique_name',
        ),
    ]
