# Generated by Django 3.2.7 on 2021-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20210920_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_name',
            field=models.CharField(default='default_group', max_length=50),
        ),
    ]
